## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1677688026@qq.com #发送邮件的邮箱地址
    password:  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587 #端口号465或587
    from: 1677688026@qq.com # 发送邮件的地址，和上面username一致可以任意
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true
  default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 100MB
      enabled: true
      max-request-size: 100MB
server:
  port: 80

papersender:
  subject: 天津农学院陈长喜老师邀请您参加考试
  content: $studentName$同学您好,您的学号$studentNo$，该邮件是由陈长喜组织发送，以邀请您参加考试，考试试卷附在该邮件的附件之中，如有问题请联系陈长喜QQ:185901012。(自动发送，请勿回复)